namespace: dit-docs

targetCustomizations:
  - name: development
    clusterSelector:
      matchLabels:
        env: dev
    kustomize:
      dir: development
  - name: production
    clusterSelector:
      matchLabels:
        env: prod
    kustomize:
      dir: production
