---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - path: patches/ingress-host.yaml
    target:
      kind: Ingress
  - path: patches/deployment.yaml
    target:
      kind: Deployment
