---
name: Deploy To Development

on:
  push:
    branches:
      - dev

    paths-ignore:
      - "README.md"
      - ".vscode/**"

      - ".github/**"
      - "!.github/workflows/tests-base.yaml"
      - "!.github/workflows/deploy-base.yaml"
      - "!.github/workflows/deploy-dev.yaml"

concurrency:
  group: deploy-dev
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/tests-base.yaml

  build:
    uses: ditkrg/build-image-workflow/.github/workflows/workflow.yaml@v1
    needs: test
    with:
      image: dit-docs/dsm-client
      runs-on: "['ubuntu-latest']"
    secrets:
      username: ${{ secrets.HARBOR_PUBLIC_USER }}
      password: ${{ secrets.HARBOR_PUBLIC_TOKEN }}

  deploy:
    uses: ./.github/workflows/deploy-base.yaml
    needs: build
    with:
      image: ${{ needs.build.outputs.tag }}
      env_url: https://service-manual.docs.dev.krd
      env_name: development

    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
